'use strict';
const $=id=>document.getElementById(id), canvas=$('board'),ctx=canvas.getContext('2d');
let state,history=[],sound=false,audio;
let completed=[];try{completed=JSON.parse(localStorage.getItem('orbita-completed')||'[]');if(!Array.isArray(completed))completed=[];}catch{}
function tone(freq=350){if(!sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(.08,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.15);o.start();o.stop(audio.currentTime+.15);}catch{}}
function rounded(x,y,w,h,r,color){ctx.fillStyle=color;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill();}
function draw(){const tile=Math.min(720/(state.width+1),600/(state.height+1)),ox=(720-state.width*tile)/2,oy=(600-state.height*tile)/2;ctx.clearRect(0,0,720,600);const ready=Puzzle.unlocked(state);for(let y=0;y<state.height;y++)for(let x=0;x<state.width;x++){const p=Puzzle.pos(x,y),px=ox+x*tile,py=oy+y*tile,cx=px+tile/2,cy=py+tile/2;rounded(px+2,py+2,tile-4,tile-4,6,state.walls.includes(p)?'#344543':'#1d2b2a');if(state.walls.includes(p)){rounded(px+7,py+6,tile-14,4,2,'#465955');continue;}if(state.targets.includes(p)){ctx.strokeStyle=state.boxes.includes(p)?'#b7f278':'#779c64';ctx.lineWidth=3;ctx.beginPath();ctx.arc(cx,cy,tile*.24,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#729659';ctx.beginPath();ctx.arc(cx,cy,3,0,Math.PI*2);ctx.fill();}if(p===state.exit){rounded(px+tile*.19,py+tile*.13,tile*.62,tile*.76,7,ready?'#b7f278':'#527268');rounded(px+tile*.29,py+tile*.23,tile*.42,tile*.66,3,ready?'#477a3f':'#152b27');ctx.fillStyle=ready?'#dbffbb':'#8cac98';ctx.beginPath();ctx.arc(px+tile*.62,cy,3,0,Math.PI*2);ctx.fill();}if(p===state.key&&!state.hasKey){ctx.strokeStyle='#efcc71';ctx.lineWidth=5;ctx.beginPath();ctx.arc(cx-6,cy-5,7,0,Math.PI*2);ctx.moveTo(cx-1,cy);ctx.lineTo(cx+11,cy+12);ctx.lineTo(cx+17,cy+6);ctx.stroke();}if(state.boxes.includes(p)){const on=state.targets.includes(p);rounded(px+tile*.13,py+tile*.16,tile*.74,tile*.74,7,'#0f1918');rounded(px+tile*.13,py+tile*.1,tile*.74,tile*.74,7,on?'#84a95f':'#ae8056');ctx.strokeStyle=on?'#c3e993':'#d2a879';ctx.lineWidth=3;ctx.strokeRect(px+tile*.23,py+tile*.2,tile*.54,tile*.54);ctx.beginPath();ctx.moveTo(px+tile*.23,py+tile*.2);ctx.lineTo(px+tile*.77,py+tile*.74);ctx.moveTo(px+tile*.77,py+tile*.2);ctx.lineTo(px+tile*.23,py+tile*.74);ctx.stroke();}if(state.player.x===x&&state.player.y===y){ctx.fillStyle='#0c1715';ctx.beginPath();ctx.ellipse(cx,cy+tile*.25,tile*.22,tile*.1,0,0,Math.PI*2);ctx.fill();rounded(px+tile*.2,py+tile*.14,tile*.6,tile*.65,12,'#b7f278');rounded(px+tile*.27,py+tile*.29,tile*.46,tile*.22,5,'#243d30');ctx.fillStyle='#efffdb';ctx.fillRect(cx-tile*.12,cy-tile*.13,3,5);ctx.fillRect(cx+tile*.08,cy-tile*.13,3,5);}}$('moves').textContent=state.moves;$('undo').disabled=!history.length;}
function progress(){const el=$('progress');el.replaceChildren();Puzzle.levels.forEach((l,i)=>{const b=document.createElement('button');b.textContent=completed.includes(i)?'✓':i+1;b.className=i===state.index?'active':completed.includes(i)?'done':'';b.setAttribute('aria-label',`Cámara ${i+1}: ${l.name}`);if(i===state.index)b.setAttribute('aria-current','step');b.onclick=()=>load(i);el.append(b);});}
function load(index){state=Puzzle.create(index);history=[];$('level-number').textContent=`CÁMARA ${String(index+1).padStart(2,'0')} / 05`;$('level-title').textContent=Puzzle.levels[index].name;$('tip').textContent=Puzzle.levels[index].tip;$('status').textContent='Recoge la llave y activa los interruptores para salir.';$('overlay').hidden=true;progress();draw();}
function step(dx,dy){const result=Puzzle.move(state,dx,dy);if(result.message)$('status').textContent=result.message;if(!result.changed)return;history.push(state);state=result.state;tone(state.won?880:result.collected?660:result.pushed?240:350);draw();if(state.won){if(!completed.includes(state.index))completed.push(state.index);try{localStorage.setItem('orbita-completed',JSON.stringify(completed));}catch{}progress();$('win-title').textContent=state.index===4?'¡Laboratorio completado!':'Cámara superada';$('win-detail').textContent=`Encontraste la salida en ${state.moves} movimientos.`;$('next').textContent=state.index===4?'Volver a jugar ↻':'Siguiente cámara →';$('overlay').hidden=false;$('next').focus();}}
function undo(){if(!history.length)return;state=history.pop();$('overlay').hidden=true;$('status').textContent='Movimiento deshecho.';draw();}
document.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey)return;const key=e.key.toLowerCase(),dirs={arrowup:[0,-1],w:[0,-1],arrowdown:[0,1],s:[0,1],arrowleft:[-1,0],a:[-1,0],arrowright:[1,0],d:[1,0]};if(dirs[key]){e.preventDefault();step(...dirs[key]);}else if(key==='z'){e.preventDefault();undo();}else if(key==='r'){load(state.index);}});
document.querySelectorAll('[data-dir]').forEach(b=>b.onclick=()=>step(...b.dataset.dir.split(',').map(Number)));
$('undo').onclick=undo;$('restart').onclick=()=>load(state.index);$('next').onclick=()=>{load((state.index+1)%Puzzle.levels.length);canvas.focus();};$('sound').onclick=()=>{sound=!sound;$('sound').textContent=`Sonido: ${sound?'encendido':'apagado'}`;$('sound').setAttribute('aria-pressed',sound);tone();};
let touchStart;canvas.addEventListener('pointerdown',e=>{touchStart={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);canvas.focus();});canvas.addEventListener('pointerup',e=>{if(!touchStart)return;const dx=e.clientX-touchStart.x,dy=e.clientY-touchStart.y;touchStart=null;if(Math.max(Math.abs(dx),Math.abs(dy))<15)return;step(...(Math.abs(dx)>Math.abs(dy)?[Math.sign(dx),0]:[0,Math.sign(dy)]));});canvas.addEventListener('pointercancel',()=>touchStart=null);
load(0);
